imports:
    - { resource: "../../../../../app/config/parameters.yml" }

parameters:
#    user.example.class: Educacity\UserBundle\Example
    user.manager.class: Educacity\UserBundle\Form\Handler\UserManager
    user.createuserformhandler.class: Educacity\UserBundle\Form\Handler\CreateUserFormHandler
    user.createsalt.class: Educacity\UserBundle\EventListener\CreateUserSaltEventSubscriber
    user.userhandler.class: Educacity\UserBundle\Form\Handler\UserHandler
    user.class: Educacity\UserBundle\Entity\User
    user.repository.class: Educacity\UserBundle\Entity\UserRepository
    user.provider.class: Educacity\UserBundle\Provider\UserProvider

services:
    user.manager:
        class: %user.manager.class%
        arguments: [@doctrine.orm.entity_manager]
    user.create_user_form_handler:
        class: %user.createuserformhandler.class%
        arguments: [@user.manager]
    user.create_salt_listener:
        class: %user.createsalt.class%
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_subscriber }
    user.handler:
        class: %user.userhandler.class%
        arguments: [@doctrine.orm.entity_manager, @form.factory, @security.encoder_factory]
    user.manager:
        class:            Doctrine\ORM\EntityManager
        factory_service:  doctrine
        factory_method:   getManagerForClass
        arguments: [%user.class%]
    user.repository:
        class: %user.repository.class%
        factory_service: user.manager
        factory_method: getRepository
        arguments: [%user.class%]
    user.provider:
        class: %user.provider.class%
        arguments: [@user.repository]